# file: tasks/configure-slaves.yml -- postgresql pre-start configuration of the slave servers and startup

- name: "Stage 3: start postgresql service"
  service: name="postgresql" state=started enabled=yes

- name: "Stage 2: restart postgresql service"
  service: name="postgresql" state=restarted enabled=yes
  when: restart_slave

- name: "Install python-psycopg2"
  apt: name=python-psycopg2 state=present

- name: "Reloading postgres configuration file for slave"
  sudo_user: postgres
  shell: psql -c "select pg_reload_conf()"
