# file: tasks/configure-slaves.yml -- postgresql pre-start configuration of the slave servers and startup

- name: "Stage 3: start postgresql service"
  service: name="postgresql" state=started enabled=yes

- name: "Install python-psycopg2"
  apt: name=python-psycopg2 state=present

