---
- hosts: db
  remote_user: ubuntu
  sudo: true
  vars:
        max_connections: 110
        temp_file_limit: 10
        listen_addresses: '*'
  handlers:
        - name: reload postgres config
          sudo_user: postgres
          shell: psql -c "select pg_reload_conf()"
  tasks:
        - name: update apt cache
          apt: update_cache=yes
          #        - include: tasks/postgresql.yml

- hosts: streaming-master
  remote_user: ubuntu
  sudo_user: root
  sudo: true
  #  vars:
  #      max_connections: 110
  #      temp_file_limit: 10
  #      listen_addresses: '*'
  vars_files:
    - 'defaults/main.yml'
  roles:
    - pg_master

- hosts: streaming-slaves
  remote_user: ubuntu
  sudo_user: root
  sudo: true
  vars_files:
   - 'defaults/main.yml'
  roles:
    - {role: slave_rebuild, when: "failover == True"}
    - {role: pg_slave, when: "failover == False"}
