---
# Install and setup PostgreSQL Streaming Replication on Enterprise Linux 6 (RHEL/CentOS/Scientific)
- hosts: all
  remote_user: ubuntu
  sudo: yes
  sudo_user: ubuntu
  vars_files:
    - 'defaults/main.yml'
    - 'defaults/repo.yml'
- hosts: streaming-master
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/main.yml'
    - 'defaults/repo.yml'
  tasks:
  - include: 'tasks/configure-master.yml'
  - include: 'tasks/users.yml'
  - include: 'tasks/databases.yml'

- hosts: streaming-slaves
  remote_user: ubuntu
  sudo: yes
  sudo_user: root
  vars_files:
    - 'defaults/main.yml'
    - 'defaults/repo.yml'
  tasks:
  - include: 'tasks/configure-slaves.yml'
