# file: tasks/configure-master.yml -- postgresql pre-start configuration of master server and startup

- name: "Stage 2: stop old postgresql service"
  service: name="postgresql" state=stopped
  when: postgresql_drop_old_cluster

- name: "Stage 2: remove old postgresql cluster"
  command: "rm -rf /var/lib/postgresql/{{ postgresql_version }}/main {{ postgresql_cluster_symlink_src }}"
  when: postgresql_drop_old_cluster

- name: "Stage 2: cluster directory replacement with symlink, check destination directory"
  file:
    path: "{{ postgresql_cluster_symlink_src }}"
    state: directory
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0700
  when: postgresql_cluster_symlink_src|length > 0
  
- name: "Stage 2: cluster directory replacement with symlink, create symlink"
  file:
    src: "{{ postgresql_cluster_symlink_src }}"
    dest: "/var/lib/postgresql/{{ postgresql_version }}/main"
    state: link
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
  when: postgresql_cluster_symlink_src|length > 0

- name: "Stage 2: initialize new postgresql cluster"
  sudo: yes
  sudo_user: "{{ postgresql_admin_user }}"
  command: "/usr/lib/postgresql/{{ postgresql_version }}/bin/initdb -D /var/lib/postgresql/{{ postgresql_version }}/main"

- name: "Stage 2: configure pg_hba.conf"
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640

- name: "Stage 2: configure postgresql.conf"
  template:
    src: ../../../templates/postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640
    # state: present

- name: "Stage 2: create postgresql log directory"
  file:
    path: "{{ postgresql_log_directory }}"
    state: directory
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0755
  when: postgresql_log_directory is defined

- name: "Stage 2: start postgresql service"
  service: name="postgresql" state=started enabled=yes

- name: "Install python-psycopg2"
  apt: name=python-psycopg2 state=present
